#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;

	
	//1. FILE pointer open & error handling
	fp = fopen("schedule.dat","r");
	if (fp == NULL)
	{
		printf("error - file isn't opened");
		return -1;
	}
	
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	//2. read from the file
	
	while ( !feof(fp) )
	{	

		int f = fscanf(fp,"%s %s %d %d %d",name, place, &type, &month, &day);

		// generate genSchedInfo structure by genSchedInfo function
		schedInfo = sched_genSchedInfo(name, place,type,month,day);
		
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);
	}
	
	// close the file pointer
	fclose(fp);  
	printf("Read done! %i schedules are read\n", list_len(list));
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		printf("\n\n\n1. print all the schedules\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in the place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n");
		
		//4. get option from keyboard
		printf("\n select an option: ");
		scanf("%d", &option);
		
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				printf("--------------------------------------------\n");
				cnt = 1;
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					ndPtr = list_getNextNd(ndPtr);     //get the object (scheduling info)
					printf("%d. ", cnt);               // print count
					schedInfo = list_getNdObj(ndPtr);  //get the next node from the list
					sched_print(schedInfo);            //print each scheduling info element
					cnt++;
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				printf("\n\n\n--------------------------------------------\n");
				
				cnt = 1;
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					
					ndPtr = list_getNextNd(ndPtr);     //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					// print scheduling info elements matching to the month 
					if (sched_getMonth(schedInfo) == month)
					{
						printf("%d. ", cnt);
						sched_print(schedInfo);
						cnt++;
					}

				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", place);
				printf("\n\n\n--------------------------------------------\n");
				
				cnt = 1;
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
				
					ndPtr = list_getNextNd(ndPtr);     //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					 
					// print scheduling info elements matching to the place
					if (strcmp(sched_getPlace(schedInfo), place)==0) 
					{
						printf("%d. ", cnt);     //print count
						sched_print(schedInfo);  // print each scheduling info element

						cnt++;
					}
					
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				printf("\n\n\n--------------------------------------------\n");
				
				/* check the type and check if the type is valid */
				if (sched_convertType(typeName)>=0 && sched_convertType(typeName) <= 5)
				{
					cnt = 1;
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{

						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)	
					
						//check the type and print scheduling info elements
						if (sched_getType(schedInfo) == sched_convertType(typeName)) 
						{
							printf("%d. ", cnt);      //print count 
							sched_print(schedInfo);    //print each scheduling info element

							cnt++;
						}

					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
